spring:
  application:
    name: defsemtp
  datasource:
    url: jdbc:h2:mem:camunda-h2-database;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console

camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
      firstname: Admin
      lastname: Admin
  webapp:
    enabled: true                   # Ensure webapps are enabled
    security-configurer-enabled: true
